# Generated by Django 2.2.4 on 2020-04-14 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_model', '0006_auto_20200406_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedChargeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChargeOffRate', models.FloatField()),
                ('Year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2100)])),
                ('Quarter', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
            ],
        ),
    ]
