# Generated by Django 2.2.4 on 2020-04-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_model', '0007_fedchargeoff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fedchargeoff',
            old_name='ChargeOffRate',
            new_name='DefaultRate',
        ),
    ]
